### ISSUE TITLE
Open Firebase Repository

### ISSUE THREAD

**Issue by matejthetree** [mokuteki-io/dart-playgrounds#13]
Open a firebase repository for dart-playgrounds.
put all necessary files inside the app. 

Initialize the firebase in `main` function.

Add correct permission for firestore database.
Add correct files for iOS and Android.

**Comment by goranesine** [comment]
If I add firebase or firebase_core in pubspec.yaml,  gradle build fail.
After some testing I remove firebase_core and import firebase_auth, 
I make a simple anonymous login and it works.
Do we need firebase_core in pubspec.yaml?

**Comment by matejthetree** [comment]
Not right now. Just auth and firestore later.

**Comment by matejthetree** [comment]
Pull request make.

**Comment by goranesine** [comment]
Should I first add login page,or make pull request?

**Comment by matejthetree** [comment]
first pull request. login in this issue is anonymus and instant.
in the next pull request we implement login
