### ISSUE TITLE
Implement Playground 

### ISSUE THREAD

**Issue by matejthetree** [mokuteki-io/dart-playgrounds#14]
Create one file called `app_config` inside the config folder.
There you will create global variable called `kAppEnvironment` ;
Under create enum `AppEnvironment { develop, production }`

in drawer, if the environment is dev, create 'Playground' below the about link. There must be horizontal separator in between.

if the environment is production, everything remains the same.

When you click on the Playground, you go to `PlaygroundPage` route.

There you have to create https://github.com/matejthetree/playground.git
import it as a library from git.

**Comment by djkowa** [comment]
finished
