### ISSUE TITLE
Create Golden Test for Splash screen widgets.

### ISSUE THREAD

**Issue by matejthetree** [mokuteki-io/dart-playgrounds#16]
Check if it is possible to create the splashScreen, and then take the golden picture after x milliseconds.

and then check if the pictures are consistent.

Ask question here if you have any

**Comment by goranesine** [comment]
I try this code, but I always get empty picture and test is always successful.
import 'package:flutter_test/flutter_test.dart';
import 'package:playground_app/main.dart';

void main() {
  testWidgets('Golden test', (WidgetTester tester) async {
    await tester.pumpWidget(MyApp());
    await expectLater(find.byType(MyApp), matchesGoldenFile('main.png'));
  });
}
Who I must call in find.byType ?

**Comment by goranesine** [comment]
I update the code,now is working.
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter/material.dart';
import 'package:playground_app/ui_pages/splash_screen.dart';

void main() {

  Widget homePageTest() {
    return MaterialApp(
      home: Center(
        child: RepaintBoundary(child: SplashScreen()),
      ),
    );
  }

  testWidgets('Golden test', (WidgetTester tester) async {
    Widget widget = homePageTest();
    await tester.pumpWidget(widget);
    await tester.pump(Duration(seconds: 3));
    await expectLater(find.byType(SplashScreen), matchesGoldenFile('main.png'));
  });
}

**Comment by matejthetree** [comment]
Ok great. Now add couple of timers to catch the widget at different times.
See if that works.

**Comment by matejthetree** [comment]
Also you can name the golden file splashScreenGolden.png

**Comment by goranesine** [comment]
I put three tests, all three tests passed the test.
Code:
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter/material.dart';
import 'package:playground_app/ui_pages/splash_screen.dart';

void main() {

  Widget homePageTest() {
    return MaterialApp(
      home: Center(
        child: RepaintBoundary(child: SplashScreen()),
      ),
    );
  }

  testWidgets('Golden test 1', (WidgetTester tester) async {
    Widget widget = homePageTest();
    await tester.pumpWidget(widget);
    await tester.pump(Duration(seconds: 1));
    await expectLater(find.byType(SplashScreen), matchesGoldenFile('splashScreenGoldenOneSecond.png'));
  });
  testWidgets('Golden test 2', (WidgetTester tester) async {
    Widget widget = homePageTest();
    await tester.pumpWidget(widget);
    await tester.pump(Duration(seconds: 2));
    await expectLater(find.byType(SplashScreen), matchesGoldenFile('splashScreenGoldenTwoSecond.png'));
  });
  testWidgets('Golden test 3', (WidgetTester tester) async {
    Widget widget = homePageTest();
    await tester.pumpWidget(widget);
    await tester.pump(Duration(seconds: 3));
    await expectLater(find.byType(SplashScreen), matchesGoldenFile('splashScreenGoldenThreeSecond.png'));
  });
}

**Comment by matejthetree** [comment]
What commands do you use to create goldens and what to test?

**Comment by goranesine** [comment]
First I generate png files with flutter test  -- update goldens then I run flutter test.

**Comment by matejthetree** [comment]
nice. ok, you can create pr for this

**Comment by goranesine** [comment]
Today I realize that tests generate failure folder with png with difference.
So the test failed, but I think is ok because text opacity is changing and
png are different.
Am I wrong?

**Comment by matejthetree** [comment]
That was the test. Will it create the same picture everytime at designated
time.

We can create this by making a pause with every text and speeding up the
opacity.
That way we have more time when opacity is the same.

I don't think it is important though at this point but it is important to
have one test that will pass.

What do you think?

**Comment by goranesine** [comment]
I will make more testings to see the results

**Comment by goranesine** [comment]
![golden_test](https://user-images.githubusercontent.com/42481446/71550302-6e131400-29cd-11ea-95d4-a46c2759b8dd.PNG)

I run test on current session,then I restart android studio and run the test again. Now all tests passed.
