### ISSUE TITLE
Create nice looking firebase

### ISSUE THREAD

**Issue by matejthetree** [mokuteki-io/dart-playgrounds#30]
Write the project name 
Add security
Add other team members to project

**Comment by goranesine** [comment]
Za sada sam ubacio samo ovaj rule.
rules_version = '2';
service cloud.firestore {

   match /users/{id} {
   allow read,write: if request.auth.uid == id;
}
  }

Dodao sam team members.
Šta si mislio pod write project name?

**Comment by goranesine** [comment]
rules_version = '2';
service cloud.firestore {

  match /databases/{database}/documents {
    match /{document=**} {
    allow create,read,write: if request.auth.uid != null
    }
  }
}

Ovo radi.

**Comment by goranesine** [comment]
To je za cijeli database, možemo posebno definirati rules za foldere.

**Comment by matejthetree** [comment]
Project name u firebaseu da bude sart playgrounds. Sada su neka skova. I
nisam dobio email da si me dodao na firebase.

**Comment by goranesine** [comment]
Riješeno
