### ISSUE TITLE
Add Continuous integration and delivery

### ISSUE THREAD

**Issue by SempaiEcchi** [mokuteki-io/dart-playgrounds#49]
Set up bitrise

**Comment by SempaiEcchi** [comment]
@djkowa  @lea88pu  @goranesine  I need your emails

**Comment by SempaiEcchi** [comment]
@matejthetree  need you approval to use this repository on bitrise, check your email

**Comment by matejthetree** [comment]
Granted

**Comment by goranesine** [comment]
goranesine@gmail.com

sub, 1. velj 2020. u 18:04 Leo Radocaj <notifications@github.com> napisao
je:
