### ISSUE TITLE
Figure out Github Project automatic assignment

### ISSUE THREAD

**Issue by matejthetree** [mokuteki-io/dart-playgrounds#50]
Inside projects you have todo in progress in review and done.

Now it works automatic when you open issue and when you close issue, but how to make it work automatic when you start pull request and when you request review?

You can open your own repository to test, and then report here finding

**Comment by SempaiEcchi** [comment]
In order to close an issue you have to reference the issue in the commit message. For example; if my pull request(branch) is regarding issue #50 I will commit and push with message "Fixes #50"
